/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-07-10 16:43:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Staff and Student Management</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"bootstrap/css/bootstrap.css\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- <script\r\n");
      out.write("\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".maincontent {\r\n");
      out.write("\tbackground-color: #A4A4F0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("option {\r\n");
      out.write("\theight: 23px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mytb td, .mytb th {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#classlist, #universitylist, #txtinput, #statuslist {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("\theight: 32px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".stuform td {\r\n");
      out.write("\tpadding: 2px;\r\n");
      out.write("\tborder: 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"maincontent col-sm-12\">\r\n");
      out.write("\t\t<div id=\"sheader\">\r\n");
      out.write("\t\t\t<div id=\"title\">\r\n");
      out.write("\t\t\t\t<h1>Staff and Student Management</h1>\r\n");
      out.write("\t\t\t\t<h4>Ke Pisal, Class Battambong</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"classlist\">\r\n");
      out.write("\t\t\t\t<label>Search By Name : </label> <input type=text id=txtinput /> <select\r\n");
      out.write("\t\t\t\t\tid=classselected onclick=\"searchClass()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"universitylist\">\r\n");
      out.write("\t\t\t\t<select id=unvselected onclick=\"searchUniversity()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"statuslist\">\r\n");
      out.write("\t\t\t\t<select id=statusselected onclick=\"searchStatus()\">\r\n");
      out.write("\t\t\t\t\t<option value=''>All Status</option>\r\n");
      out.write("\t\t\t\t\t<option value=1>Active</option>\r\n");
      out.write("\t\t\t\t\t<option value=0>Deactive</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"sform\">\r\n");
      out.write("\t\t\t<table class=\"stuform\">\r\n");
      out.write("\t\t\t<h3><i>Student Data</i></h3>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><i>Student Id</i></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;:<input /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><i>Student Name </i></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;:<input /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><i>Student Gender </i></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;:<input /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><i>Student University </i></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;:<input /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><i>Student Class </i></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;:<input /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><i>Student Status </i></td>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;&nbsp;:<input /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\"><button id=\"btnadd btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"add()\">Submit</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"btnclear btn btn-success\" onclick=\"add()\">Clear</button></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"sbody\">\r\n");
      out.write("\t\t\t<table class=\"mytb col-sm-12\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t<th>NAME</th>\r\n");
      out.write("\t\t\t\t\t\t<th>GENDER</th>\r\n");
      out.write("\t\t\t\t\t\t<th>UNIVERSITY</th>\r\n");
      out.write("\t\t\t\t\t\t<th>CLASS</th>\r\n");
      out.write("\t\t\t\t\t\t<th>STATUS</th>\r\n");
      out.write("\t\t\t\t\t\t<th>OPERATION</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody id=\"tblist\">\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div id=\"sdetails\">\r\n");
      out.write("\t\t\t\t<!-- <i><h2>-------------Information Detail------------</h2></i> <label>ID\r\n");
      out.write("\t\t\t\t:</label>\r\n");
      out.write("\t\t\t<h3 id=\"stuid\"></h3>\r\n");
      out.write("\t\t\t<label>NAME :</label>\r\n");
      out.write("\t\t\t<h3 id=\"stuname\"></h3>\r\n");
      out.write("\t\t\t<label>GENDER :</label>\r\n");
      out.write("\t\t\t<h3 id=\"stugender\"></h3>\r\n");
      out.write("\t\t\t<label>UINVERSITY :</label>\r\n");
      out.write("\t\t\t<h3 id=\"stuuniversity\"></h3>\r\n");
      out.write("\t\t\t<label>CLASS :</label>\r\n");
      out.write("\t\t\t<h3 id=\"stuclass\"></h3>\r\n");
      out.write("\t\t\t<label>STATUS :</label>\r\n");
      out.write("\t\t\t<h3 id=\"stustatus\">ss</h3>\r\n");
      out.write("\t\t\t<i><h2>-------------Information Detail------------</h2></i> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-3\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
